# See https://github.com/psycopg/psycopg2/blob/master/.github/workflows/packages.yml

name: psycopg2-binary

on: [workflow_dispatch]

env:
  VERSION: 2_9_5
  CIBW_BUILD: nogil39-*
  CIBW_ARCHS_LINUX: auto
  CIBW_ARCHS_MACOS: universal2
  CIBW_ARCHS_WINDOWS: AMD64

jobs:
  build-manylinux:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - {tag: manylinux2014, arch: x86_64, os: ubuntu-latest}

    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'psycopg/psycopg2'
          ref: ${{ env.VERSION }}

      - name: Build packages
        run: >-
          docker run --rm
          -e PLAT=${{ matrix.tag }}_${{ matrix.arch }}
          -e PACKAGE_NAME=psycopg2-binary
          -e PYVERS="nogil39-nogil_39b_x86_64_linux_gnu"
          -e PSYCOPG2_TESTDB=postgres
          -e PSYCOPG2_TESTDB_HOST=172.17.0.1
          -e PSYCOPG2_TESTDB_USER=postgres
          -e PSYCOPG2_TESTDB_PASSWORD=password
          -e PSYCOPG2_TEST_FAST=1
          -v `pwd`:/src
          --workdir /src
          nogil/${{ matrix.tag }}_${{ matrix.arch }}
          ./scripts/build/build_${{ matrix.tag }}.sh

      - uses: actions/upload-artifact@v3
        with:
          path: dist/*/*${{ matrix.tag }}_${{ matrix.arch }}.whl

    services:
      postgresql:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'psycopg/psycopg2'
          ref: ${{ env.VERSION }}

      - name: Set up Python
        uses: colesbury/setup-python@nogil
        with:
          python-version: 'nogil-3.9'

      - name: Build packages
        run: ./scripts/build/build_macos.sh
        env:
          PACKAGE_NAME: psycopg2-binary
          PSYCOPG2_TESTDB: postgres
          PSYCOPG2_TEST_FAST: 1

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          path: dist/*/*.whl

  upload_wheel:
    needs: [build-manylinux, build-macos]
    uses: ./.github/workflows/upload-wheel.yml
    with:
      AWS_BUCKET: pypi-test.sam-gross.com
    secrets: inherit
