# See https://github.com/pydantic/pydantic/blob/1.10.X-fixes/.github/workflows/ci.yml

name: pydantic

on: [workflow_dispatch]

env:
  VERSION: 1.10.3
  CIBW_BUILD: nogil39-*
  CIBW_ARCHS_LINUX: auto
  CIBW_ARCHS_MACOS: universal2
  CIBW_ARCHS_WINDOWS: AMD64
  CIBW_BEFORE_BUILD: 'pip install -U cython'
  CIBW_TEST_REQUIRES: 'pytest==6.2.5 pytest-mock==3.6.1'
  # Test case fails due to different behavior with overlapping fields
  CIBW_TEST_COMMAND: 'pytest -k "not test_private_attribute_intersection_with_extra_field" {project}/tests'

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-12]

    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'pydantic/pydantic'
          ref: v${{ env.VERSION }}

      - name: Build wheels
        uses: colesbury/cibuildwheel@nogil

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

  upload_wheel:
    needs: [build_wheels]
    uses: ./.github/workflows/upload-wheel.yml
    secrets: inherit
