# See https://github.com/pytorch/pytorch/blob/master/.github/workflows/generated-macos-binary-wheel-nightly.yml

name: pytorch-macos

on:
  workflow_dispatch:

jobs:
  build_macos_x86_64:
    uses: ./.github/workflows/pytorch-cpu.yml
    secrets: inherit
    with:
      BUILD_ENVIRONMENT: macos-binary-wheel

  build_macos_arm64:
    uses: ./.github/workflows/pytorch-cpu.yml
    secrets: inherit
    with:
      BUILD_ENVIRONMENT: macos-arm64-binary-wheel
      CROSS_COMPILE_ARM64: 1

  upload_wheel:
    needs: [build_macos_x86_64, build_macos_arm64]
    uses: ./.github/workflows/upload-wheel.yml
    secrets: inherit
    with:
      package: torch
