# See https://github.com/gaogaotiantian/viztracer/blob/master/.github/workflows/release.yml
# NOTE: newer versions won't work because of incompatible python_compat.h header

name: viztracer

on: [workflow_dispatch]

env:
  VERSION: 0.15.4
  CIBW_BUILD: nogil39-*
  CIBW_ARCHS_LINUX: auto
  CIBW_ARCHS_MACOS: universal2
  CIBW_ARCHS_WINDOWS: AMD64

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-12]

    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'gaogaotiantian/viztracer'
          ref: ${{ env.VERSION }}

      - name: Build wheels
        uses: colesbury/cibuildwheel@nogil

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

  upload_wheel:
    needs: [build_wheels]
    uses: ./.github/workflows/upload-wheel.yml
    secrets: inherit
